# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f1b2ed5c561d181ff898d46bbc0cc2d40f1ac3841b3d817a3415331942b04f7e10e73c9481e62384a78644509b92744df4bf0a3d4a99db93d91158375240ff

test:
  secret_key_base: 865cbbad0461efe0798c1181675aa46739f3111f63598e61936c484147237fbe4d86f9b441a526c1ea008184302e175bf933fb7e394fc2240433d254f91de847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
